const FinalTheme = () => ({

  outer: {
    overflow: 'hidden',
  },
  Window: {
    margin: '14px 0px 0px 19px',
  },
  IconStack: {
    display: 'flex',
    flexDirection: 'column',
    width: '6vw',
    height: '100vh',
    marginLeft: '20px',
    backgroundColor: '#2A2927',
    position: 'fixed',
    right: '0px',
  },
  Homeicon: {
    height: '22px',
    width: '24px',
    padding: '5px',
    backgroundColor: 'white',
    marginBottom: '50px',
    marginTop: '150px',
    marginLeft: '20px',
    borderRadius: '33px',
  },
  peopleicon: (isActive) => ({
    height: '22px',
    width: '24px',
    padding: '5px',
    backgroundColor: 'white',
    boxShadow: isActive ? '0px 0px 4px 8px' : 'none',
    marginBottom: '50px',
    cursor: 'pointer',
    marginLeft: '20px',
    borderRadius: '33px',
  }),
  Shareicon: {
    height: '22px',
    width: '24px',
    padding: '5px',
    backgroundColor: 'white',
    marginBottom: '50px',
    marginLeft: '20px',
    borderRadius: '33px',
  },
  Messageicon: (isActive) => ({
    height: '22px',
    width: '24px',
    padding: '5px',
    backgroundColor: 'white',
    boxShadow: isActive ? '0px 0px 4px 8px' : 'none',
    marginBottom: '50px',
    cursor: 'pointer',
    marginLeft: '20px',
    borderRadius: '33px',
  }),
  CallIcon: {
    height: '22px',
    width: '24px',
    padding: '5px',
    backgroundColor: 'red',
    marginBottom: '50px',
    marginLeft: '20px',
    borderRadius: '33px',
  },
  Micicon: {
    height: '22px',
    width: '24px',
    padding: '5px',
    backgroundColor: 'white',
    marginBottom: '50px',
    marginLeft: '20px',
    borderRadius: '33px',
  },
});

export default FinalTheme;
